### PR TITLE
Add Issue Template

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added an issue template for your repository. This template has four issues namely bug, documentation, feature, proposal.

### CODE REVIEW

**Comment by avidraghav** [comment]
can u add template about enhancement label too?

**Comment by avidraghav** [comment]
What is neoalgo in proposal.md file? The templates that u have made are very simple and not much helpful, it would be better if u can make some templates with specific and useful headings.

**Comment by muthuannamalai12** [comment]
I have changed  Neo algo to Qsol. I can add for enhancement I will try to modify it

**Comment by muthuannamalai12** [comment]
I have changed it. Kindly check it @raghavagg01

**Comment by muthuannamalai12** [comment]
@raghavagg01. Kindly pls add the same labels present in my issue to pr also
So kindly do add DWOC and Level-1 label

**Pull request merged**
